export const FOOD_PAYLOAD_CONSTANT = {
  companyId: 0,
  companyFoodTypesOrder: [
    {
      companyID: 0,
      companyName: 'string',
      foodTypes: 'breakfast',
      foodtypeID: 1,
      status: false,
    },
    {
      companyID: 0,
      companyName: 'string',
      foodTypes: 'lunch',
      foodtypeID: 2,
      status: false,
    },
    {
      companyID: 0,
      companyName: 'string',
      foodTypes: 'potluck',
      foodtypeID: 3,
      status: false,
    },
    {
      companyID: 0,
      companyName: 'string',
      foodTypes: 'dinner',
      foodtypeID: 4,
      status: false,
    },
  ],
  companyFoodWeekDaysOrder: [
    {
      compId: 0,
      companyName: 'string',
      employeeCount: 0,
      foodTypeCount: 0,
      foodTypeName: 'string',
      weekDaysCount: 0,
      weekDayName: 'monday',
      weekDayId: 1,
      status:false,
    },
    {
      compId: 0,
      companyName: 'string',
      employeeCount: 0,
      foodTypeCount: 0,
      foodTypeName: 'string',
      weekDaysCount: 0,
      weekDayName: 'tuesday',
      weekDayId: 2,
      status: false,
    },
    {
      compId: 0,
      companyName: 'string',
      employeeCount: 0,
      foodTypeCount: 0,
      foodTypeName: 'string',
      weekDaysCount: 0,
      weekDayName: 'wednesday',
      weekDayId: 3,
      status: false,
    },
    {
      compId: 0,
      companyName: 'string',
      employeeCount: 0,
      foodTypeCount: 0,
      foodTypeName: 'string',
      weekDaysCount: 0,
      weekDayName: 'thursday',
      weekDayId: 4,
      status: false,
    },
    {
      compId: 0,
      companyName: 'string',
      employeeCount: 0,
      foodTypeCount: 0,
      foodTypeName: 'string',
      weekDaysCount: 0,
      weekDayName: 'friday',
      weekDayId: 5,
      status: false,
    },
    {
      compId: 0,
      companyName: 'string',
      employeeCount: 0,
      foodTypeCount: 0,
      foodTypeName: 'string',
      weekDaysCount: 0,
      weekDayName: 'saturday',
      weekDayId: 6,
      status: false,
    }
   
  ],
};
